---
- name: Setup local environment
  hosts: localhost
  
  tasks:
  - name: Inject Secrets into docker-compose from Ansible Vault
    script: {{ playbook_dir }}/inject_secrets.py {{ playbook_dir }}/docker-compose.yml
    args:
      executable: /usr/bin/python3
    environment:
      CONTAINER_PORT: "{{ CONTAINER_PORT }}"
      CONTAINER_SHARD: "{{ CONTAINER_SHARD }}"
      MONGO_HOST: "{{ MONGO_HOST }}"
      MONGO_USER: "{{ MONGO_USER }}"
      MONGO_PASS: "{{ MONGO_PASS }}"
      DNN_HOST: "{{ DNN_HOST }}"
      DNN_PORT: "{{ DNN_PORT }}"
    register: injection_logs

  - name: Print Secret injection logs
    ansible.builtin.debug:
      var: injection_logs

- name: Startup services
  hosts: localhost

  tasks:
  - name: Shutdown active services
    community.docker.docker_compose:
      project_src: {{ playbook_dir }}
      state: absent
  
  - name: Build and startup services
    community.docker.docker_compose:
      project_src: {{ playbook_dir }}
      state: present
    register: compose_logs
  
  - name: Show output
    ansible.builtin.debug:
      var: compose_logs

  - name: Verify that Backend is running
    ansible.builtin.assert:
      that:
        - "compose_logs.services.web.masknet-api.state.running"
