---
- name: Setup local environment
  hosts: localhost
  
  tasks:
  - name: Inject Secrets into docker-compose from Ansible Vault
    script: ./inject_secrets.py ./docker-compose.yml
    args:
      executable: /usr/bin/python3
    environment:
      CONTAINER_PORT: "{{ CONTAINER_PORT }}"
      CONTAINER_SHARD: "{{ CONTAINER_SHARD }}"
      MONGO_HOST: "{{ MONGO_HOST }}"
      MONGO_USER: "{{ MONGO_USER }}"
      MONGO_PASS: "{{ MONGO_PASS }}"
      DNN_HOST: "{{ DNN_HOST }}"
      DNN_PORT: "{{ DNN_PORT }}"
    register: injection_logs

  - name: Print Secret injection logs
    debug:
      var: injection_logs.stdout
