---
- name: Setup local environment
  hosts: localhost
  
  tasks:
  - name: Inject Secrets into docker-compose from Ansible Vault
    script: "{{ playbook_dir }}/inject_secrets.py {{ playbook_dir }}/docker-compose.yml"
    args:
      executable: /usr/bin/python3
    environment:
      CONTAINER_PORT: "{{ CONTAINER_PORT }}"
      CONTAINER_SHARD: "{{ CONTAINER_SHARD }}"
      MONGO_HOST: "{{ MONGO_HOST }}"
      MONGO_USER: "{{ MONGO_USER }}"
      MONGO_PASS: "{{ MONGO_PASS }}"
      DNN_HOST: "{{ DNN_HOST }}"
      DNN_PORT: "{{ DNN_PORT }}"
    register: injection_logs

  - name: Print Secret injection logs
    ansible.builtin.debug:
      var: injection_logs

  - name: Install Docker SDK for Python
    ansible.builtin.pip:
      name: 
        - "docker==6.1.3"
        - "docker-compose"
  
  - name: Log into GitHub Container Registry
    docker_login:
      registry: ghcr.io
      username: Havlong
      password: "{{ GITHUB_TOKEN }}"

- name: Startup services
  hosts: localhost

  tasks:
  - name: Shutdown active services
    community.docker.docker_compose:
      project_src: "{{ playbook_dir }}"
      state: absent
  
  - name: Build and startup services
    community.docker.docker_compose:
      project_src: "{{ playbook_dir }}"
      state: present
      pull: true
    register: compose_logs
  
  - name: Show output
    ansible.builtin.debug:
      var: compose_logs
