version: '3.4'
services:
  <<MONGO_HOST>>:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: <<MONGO_USER>>
      MONGO_INITDB_ROOT_PASSWORD: <<MONGO_PASS>>
    command: >
      mongo -u <<MONGO_USER>> -p "<<MONGO_PASS>>" --eval 'db.grantRolesToUser( "<<MONGO_USER>>", [ { role: "readWrite", db: "dnn" } ] );' admin
    networks:
     - masknet
    logging:
      driver: json-file
  <<DNN_HOST>>:
    image: ghcr.io/havlong/masknet-dnn
    networks:
     - masknet
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
  masknet-api:
    image: ghcr.io/havlong/masknet-api
    ports:
      - "<<CONTAINER_PORT>>:<<CONTAINER_PORT>>"
    networks:
      - masknet
    logging:
      driver: json-file

networks:
  masknet: