version: '3.4'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: havlongdb
    command: >
      mongo -u mongo -p havlongdb --eval 'db.grantRolesToUser( "mongo", [ { role: "readWrite", db: "dnn" } ] );' admin
    networks:
     - masknet
    logging:
      driver: json-file
  masknet:
    image: ghcr.io/havlong/masknet-dnn
    networks:
     - masknet
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  masknet-api:
    image: ghcr.io/havlong/masknet-api
    ports:
      - "8081:8081"
    networks:
      - masknet
    logging:
      driver: json-file

networks:
  masknet: