spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration


server:
    port: 8080

app:
  shardid: 5
  dnn_hostname: "127.0.0.1"
  dnn_port: 8081
